name: Android CI & Release Build

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    name: Build APK AAB BIN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Build Release
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleRelease :app:bundleRelease

      - name: Prepare signing
        run: |
          mkdir signing
          echo "${{ secrets.SIGNING_KEY_PK8 }}" | base64 -d > signing/key.pk8
          echo "${{ secrets.SIGNING_CERT_PEM }}" > signing/cert.pem

      - name: Generate Bazaar BIN
        run: |
          wget -q https://github.com/Cafebazaar/bundlesigner/releases/download/v0.1.13/bundlesigner-0.1.13.jar -O bundlesigner.jar

          java -jar bundlesigner.jar genbin \
          -v \
          --v2-signing-enabled true \
          --v3-signing-enabled false \
          --bundle app/build/outputs/bundle/release/*.aab \
          --bin app/build/outputs/bundle/release \
          --key signing/key.pk8 \
          --cert signing/cert.pem

      - name: Upload APK AAB BIN
        uses: actions/upload-artifact@v4
        with:
          name: ChallengeArena-release-files
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/bundle/release/*.bin
